dbt_tool:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASS') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
  target: dev